openapi: 3.0.0
info:
  title: Heroku Platform API - Accounts
  description: The platform API empowers developers to automate, extend and combine Heroku with other services.
  version: v0
servers:
- url: https://api.heroku.com
paths:
  /account/features/{account_feature_identity}:
    get:
      summary: Info
      description: Info for an existing account feature.
      operationId: account_featureInfo
      tags:
      - accounts
      parameters:
      - name: account_feature_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of account-feature.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account-feature'
      x-stackQL-resource: account-feature
      x-stackQL-method: Info
      x-stackQL-verb: select
    patch:
      summary: Update
      description: Update an existing account feature.
      operationId: account_featureUpdate
      tags:
      - accounts
      parameters:
      - name: account_feature_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of account-feature.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account-feature'
      x-stackQL-resource: account-feature
      x-stackQL-method: Update
      x-stackQL-verb: update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                enabled:
                  $ref: '#/components/schemas/enabled'
              required:
              - enabled
              type:
              - object
  /account/features:
    get:
      summary: List
      description: List existing account features.
      operationId: account_featureList
      tags:
      - accounts
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/account-feature'
                type:
                - array
      x-stackQL-resource: account-feature
      x-stackQL-method: List
      x-stackQL-verb: select
  /account:
    get:
      summary: Info
      description: Info for account.
      operationId: accountInfo
      tags:
      - accounts
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
      x-stackQL-resource: account
      x-stackQL-method: Info
      x-stackQL-verb: select
    patch:
      summary: Update
      description: Update account.
      operationId: accountUpdate
      tags:
      - accounts
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
      x-stackQL-resource: account
      x-stackQL-method: Update
      x-stackQL-verb: update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                allow_tracking:
                  $ref: '#/components/schemas/allow_tracking'
                beta:
                  $ref: '#/components/schemas/beta'
                name:
                  $ref: '#/components/schemas/name'
              type:
              - object
    delete:
      summary: Delete
      description: 'Delete account. Note that this action cannot be undone. Note: This endpoint requires the HTTP_HEROKU_PASSWORD
        or HTTP_HEROKU_PASSWORD_BASE64 header be set correctly for the user account.'
      operationId: accountDelete
      tags:
      - accounts
      parameters: []
      responses:
        '204':
          description: No Content
      x-stackQL-resource: account
      x-stackQL-method: Delete
      x-stackQL-verb: delete
  /users/{account_identity}:
    get:
      summary: Info By User
      description: Info for account.
      operationId: accountInfoByUser
      tags:
      - accounts
      parameters:
      - name: account_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of account.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
      x-stackQL-resource: account
      x-stackQL-method: InfoByUser
      x-stackQL-verb: select
    patch:
      summary: Update By User
      description: Update account.
      operationId: accountUpdateByUser
      tags:
      - accounts
      parameters:
      - name: account_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of account.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
      x-stackQL-resource: account
      x-stackQL-method: UpdateByUser
      x-stackQL-verb: update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                allow_tracking:
                  $ref: '#/components/schemas/allow_tracking'
                beta:
                  $ref: '#/components/schemas/beta'
                name:
                  $ref: '#/components/schemas/name'
              type:
              - object
    delete:
      summary: Delete By User
      description: 'Delete account. Note that this action cannot be undone. Note: This endpoint requires the HTTP_HEROKU_PASSWORD
        or HTTP_HEROKU_PASSWORD_BASE64 header be set correctly for the user account.'
      operationId: accountDeleteByUser
      tags:
      - accounts
      parameters:
      - name: account_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of account.
      responses:
        '204':
          description: No Content
      x-stackQL-resource: account
      x-stackQL-method: DeleteByUser
      x-stackQL-verb: delete
components:
  schemas:
    account-feature:
      description: An account feature represents a Heroku labs capability that can be enabled or disabled for an account on
        Heroku.
      type:
      - object
      properties:
        created_at:
          $ref: '#/components/schemas/created_at'
        description:
          $ref: '#/components/schemas/description'
        doc_url:
          $ref: '#/components/schemas/doc_url'
        enabled:
          $ref: '#/components/schemas/enabled'
        id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/name'
        state:
          $ref: '#/components/schemas/state'
        updated_at:
          $ref: '#/components/schemas/updated_at'
        display_name:
          $ref: '#/components/schemas/display_name'
        feedback_email:
          $ref: '#/components/schemas/feedback_email'
    created_at:
      description: when account feature was created
      format: date-time
      readOnly: true
      type:
      - string
    description:
      description: description of account feature
      readOnly: true
      type:
      - string
    doc_url:
      description: documentation URL of account feature
      readOnly: true
      type:
      - string
    enabled:
      description: whether or not account feature has been enabled
      readOnly: false
      type:
      - boolean
    id:
      description: unique identifier of account feature
      format: uuid
      readOnly: true
      type:
      - string
    name:
      description: unique name of account feature
      readOnly: true
      type:
      - string
    state:
      description: state of account feature
      readOnly: true
      type:
      - string
    updated_at:
      description: when account feature was updated
      format: date-time
      readOnly: true
      type:
      - string
    display_name:
      description: user readable feature name
      readOnly: true
      type:
      - string
    feedback_email:
      description: e-mail to send feedback about the feature
      readOnly: true
      type:
      - string
    account:
      description: An account represents an individual signed up to use the Heroku platform.
      type:
      - object
      properties:
        allow_tracking:
          $ref: '#/components/schemas/allow_tracking'
        beta:
          $ref: '#/components/schemas/beta'
        created_at:
          $ref: '#/components/schemas/created_at'
        email:
          $ref: '#/components/schemas/email'
        federated:
          $ref: '#/components/schemas/federated'
        id:
          $ref: '#/components/schemas/id'
        identity_provider:
          description: Identity Provider details for federated users.
          properties:
            id:
              $ref: '#/components/schemas/id'
            name:
              $ref: '#/components/schemas/name'
            team:
              type:
              - object
              properties:
                name:
                  $ref: '#/components/schemas/name'
            organization:
              type:
              - object
              properties:
                name:
                  $ref: '#/components/schemas/name'
            owner:
              $ref: '#/components/schemas/owner'
          type:
          - object
          - 'null'
        last_login:
          $ref: '#/components/schemas/last_login'
        name:
          $ref: '#/components/schemas/name'
        sms_number:
          $ref: '#/components/schemas/sms_number'
        suspended_at:
          $ref: '#/components/schemas/suspended_at'
        delinquent_at:
          $ref: '#/components/schemas/delinquent_at'
        two_factor_authentication:
          $ref: '#/components/schemas/two_factor_authentication'
        updated_at:
          $ref: '#/components/schemas/updated_at'
        verified:
          $ref: '#/components/schemas/verified'
        country_of_residence:
          $ref: '#/components/schemas/country_of_residence'
        default_organization:
          description: team selected by default
          properties:
            id:
              $ref: '#/components/schemas/id'
            name:
              $ref: '#/components/schemas/name'
          type:
          - object
          - 'null'
        default_team:
          description: team selected by default
          properties:
            id:
              $ref: '#/components/schemas/id'
            name:
              $ref: '#/components/schemas/name'
          type:
          - object
          - 'null'
    allow_tracking:
      default: true
      description: whether to allow third party web activity tracking
      readOnly: false
      type:
      - boolean
    beta:
      default: false
      description: whether allowed to utilize beta Heroku features
      readOnly: false
      type:
      - boolean
  securitySchemes:
    herokuAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
  x-stackQL-resources:
    account-feature:
      id: heroku.accounts.account-feature
      name: account-feature
      title: Account Feature
      methods:
        Info:
          operation:
            $ref: '#/paths/~1account~1features~1{account_feature_identity}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        Update:
          operation:
            $ref: '#/paths/~1account~1features~1{account_feature_identity}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        List:
          operation:
            $ref: '#/paths/~1account~1features/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/account-feature/methods/Info'
        - $ref: '#/components/x-stackQL-resources/account-feature/methods/List'
        insert: []
        update:
        - $ref: '#/components/x-stackQL-resources/account-feature/methods/Update'
        delete: []
        exec: []
    account:
      id: heroku.accounts.account
      name: account
      title: Account
      methods:
        Info:
          operation:
            $ref: '#/paths/~1account/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        Update:
          operation:
            $ref: '#/paths/~1account/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        Delete:
          operation:
            $ref: '#/paths/~1account/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        InfoByUser:
          operation:
            $ref: '#/paths/~1users~1{account_identity}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        UpdateByUser:
          operation:
            $ref: '#/paths/~1users~1{account_identity}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        DeleteByUser:
          operation:
            $ref: '#/paths/~1users~1{account_identity}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/account/methods/Info'
        - $ref: '#/components/x-stackQL-resources/account/methods/InfoByUser'
        insert: []
        update:
        - $ref: '#/components/x-stackQL-resources/account/methods/Update'
        - $ref: '#/components/x-stackQL-resources/account/methods/UpdateByUser'
        delete:
        - $ref: '#/components/x-stackQL-resources/account/methods/Delete'
        - $ref: '#/components/x-stackQL-resources/account/methods/DeleteByUser'
        exec: []
security:
- herokuAuth: []
