openapi: 3.0.0
info:
  title: Heroku Platform API - Collaborators
  description: The platform API empowers developers to automate, extend and combine Heroku with other services.
  version: v0
servers:
- url: https://api.heroku.com
paths:
  /apps/{app_identity}/collaborators:
    post:
      summary: Create
      description: Create a new collaborator.
      operationId: collaboratorCreate
      tags:
      - collaborators
      parameters:
      - name: app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of app.
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator'
      x-stackQL-resource: collaborator
      x-stackQL-method: Create
      x-stackQL-verb: insert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                silent:
                  $ref: '#/components/schemas/silent'
                user:
                  $ref: '#/components/schemas/identity'
              required:
              - user
              type:
              - object
    get:
      summary: List
      description: List existing collaborators.
      operationId: collaboratorList
      tags:
      - collaborators
      parameters:
      - name: app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of app.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/collaborator'
                type:
                - array
      x-stackQL-resource: collaborator
      x-stackQL-method: List
      x-stackQL-verb: select
  /apps/{app_identity}/collaborators/{collaborator_identity}:
    delete:
      summary: Delete
      description: Delete an existing collaborator.
      operationId: collaboratorDelete
      tags:
      - collaborators
      parameters:
      - name: app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of app.
      - name: collaborator_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of collaborator.
      responses:
        '204':
          description: No Content
      x-stackQL-resource: collaborator
      x-stackQL-method: Delete
      x-stackQL-verb: delete
    get:
      summary: Info
      description: Info for existing collaborator.
      operationId: collaboratorInfo
      tags:
      - collaborators
      parameters:
      - name: app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of app.
      - name: collaborator_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of collaborator.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/collaborator'
      x-stackQL-resource: collaborator
      x-stackQL-method: Info
      x-stackQL-verb: select
  /teams/apps/{app_identity}/collaborators:
    post:
      summary: Create
      description: Create a new collaborator on a team app. Use this endpoint instead of the `/apps/{app_id_or_name}/collaborator`
        endpoint when you want the collaborator to be granted [permissions] (https://devcenter.heroku.com/articles/org-users-access#roles-and-permissions)
        according to their role in the team.
      operationId: team_app_collaboratorCreate
      tags:
      - collaborators
      parameters:
      - name: app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of app.
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/team-app-collaborator'
      x-stackQL-resource: team-app-collaborator
      x-stackQL-method: Create
      x-stackQL-verb: insert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                permissions:
                  type:
                  - array
                  items:
                    $ref: '#/components/schemas/name'
                  description: An array of permissions to give to the collaborator.
                silent:
                  $ref: '#/components/schemas/silent'
                user:
                  $ref: '#/components/schemas/identity'
              required:
              - user
              type:
              - object
  /teams/apps/{team_app_identity}/collaborators/{team_app_collaborator_identity}:
    delete:
      summary: Delete
      description: Delete an existing collaborator from a team app.
      operationId: team_app_collaboratorDelete
      tags:
      - collaborators
      parameters:
      - name: team_app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of team-app.
      - name: team_app_collaborator_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of team-app-collaborator.
      responses:
        '204':
          description: No Content
      x-stackQL-resource: team-app-collaborator
      x-stackQL-method: Delete
      x-stackQL-verb: delete
    get:
      summary: Info
      description: Info for a collaborator on a team app.
      operationId: team_app_collaboratorInfo
      tags:
      - collaborators
      parameters:
      - name: team_app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of team-app.
      - name: team_app_collaborator_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of team-app-collaborator.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/team-app-collaborator'
      x-stackQL-resource: team-app-collaborator
      x-stackQL-method: Info
      x-stackQL-verb: select
    patch:
      summary: Update
      description: Update an existing collaborator from a team app.
      operationId: team_app_collaboratorUpdate
      tags:
      - collaborators
      parameters:
      - name: team_app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of team-app.
      - name: team_app_collaborator_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of team-app-collaborator.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/team-app-collaborator'
      x-stackQL-resource: team-app-collaborator
      x-stackQL-method: Update
      x-stackQL-verb: update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                permissions:
                  type:
                  - array
                  items:
                    $ref: '#/components/schemas/name'
                  description: An array of permissions to give to the collaborator.
              required:
              - permissions
              type:
              - object
  /teams/apps/{team_app_identity}/collaborators:
    get:
      summary: List
      description: List collaborators on a team app.
      operationId: team_app_collaboratorList
      tags:
      - collaborators
      parameters:
      - name: team_app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of team-app.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/team-app-collaborator'
                type:
                - array
      x-stackQL-resource: team-app-collaborator
      x-stackQL-method: List
      x-stackQL-verb: select
components:
  schemas:
    collaborator:
      description: A collaborator represents an account that has been given access to an app on Heroku.
      additionalProperties: false
      required:
      - app
      - created_at
      - id
      - updated_at
      - user
      type:
      - object
      properties:
        app:
          description: app collaborator belongs to
          properties:
            name:
              $ref: '#/components/schemas/name'
            id:
              $ref: '#/components/schemas/id'
          type:
          - object
        created_at:
          $ref: '#/components/schemas/created_at'
        id:
          $ref: '#/components/schemas/id'
        permissions:
          type:
          - array
          items:
            $ref: '#/components/schemas/team-app-permission'
        role:
          $ref: '#/components/schemas/role'
        updated_at:
          $ref: '#/components/schemas/updated_at'
        user:
          description: identity of collaborated account
          properties:
            email:
              $ref: '#/components/schemas/email'
            federated:
              $ref: '#/components/schemas/federated'
            id:
              $ref: '#/components/schemas/id'
          type:
          - object
    name:
      description: unique name of app
      pattern: ^[a-z][a-z0-9-]{1,28}[a-z0-9]$
      readOnly: false
      type:
      - string
    id:
      description: unique identifier of app
      format: uuid
      readOnly: true
      type:
      - string
    created_at:
      description: when collaborator was created
      format: date-time
      readOnly: true
      type:
      - string
    team-app-permission:
      description: A team app permission is a behavior that is assigned to a user in a team app.
      type:
      - object
      properties:
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
    role:
      description: role in the team
      enum:
      - admin
      - collaborator
      - member
      - owner
      - null
      readOnly: true
      type:
      - 'null'
      - string
    updated_at:
      description: when collaborator was updated
      format: date-time
      readOnly: true
      type:
      - string
    email:
      description: unique email address of account
      format: email
      readOnly: false
      type:
      - string
    federated:
      description: whether the user is federated and belongs to an Identity Provider
      readOnly: true
      type:
      - boolean
    silent:
      default: false
      description: whether to suppress email invitation when creating collaborator
      readOnly: false
      type:
      - boolean
    identity:
      anyOf:
      - $ref: '#/components/schemas/email'
      - $ref: '#/components/schemas/id'
      - $ref: '#/components/schemas/self'
    self:
      description: Implicit reference to currently authorized user
      enum:
      - '~'
      readOnly: true
      type:
      - string
    team-app-collaborator:
      description: A team collaborator represents an account that has been given access to a team app on Heroku.
      type:
      - object
      properties:
        app:
          description: app collaborator belongs to
          properties:
            name:
              $ref: '#/components/schemas/name'
            id:
              $ref: '#/components/schemas/id'
          type:
          - object
        created_at:
          $ref: '#/components/schemas/created_at'
        id:
          $ref: '#/components/schemas/id'
        permissions:
          type:
          - array
          items:
            $ref: '#/components/schemas/team-app-permission'
          description: array of permissions for the collaborator (only applicable if the app is on a team)
        role:
          $ref: '#/components/schemas/role'
        updated_at:
          $ref: '#/components/schemas/updated_at'
        user:
          description: identity of collaborated account
          properties:
            email:
              $ref: '#/components/schemas/email'
            federated:
              $ref: '#/components/schemas/federated'
            id:
              $ref: '#/components/schemas/id'
          type:
          - object
  securitySchemes:
    herokuAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
  x-stackQL-resources:
    collaborator:
      id: heroku.collaborators.collaborator
      name: collaborator
      title: Collaborator
      methods:
        Create:
          operation:
            $ref: '#/paths/~1apps~1{app_identity}~1collaborators/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        List:
          operation:
            $ref: '#/paths/~1apps~1{app_identity}~1collaborators/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        Delete:
          operation:
            $ref: '#/paths/~1apps~1{app_identity}~1collaborators~1{collaborator_identity}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        Info:
          operation:
            $ref: '#/paths/~1apps~1{app_identity}~1collaborators~1{collaborator_identity}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/collaborator/methods/List'
        - $ref: '#/components/x-stackQL-resources/collaborator/methods/Info'
        insert:
        - $ref: '#/components/x-stackQL-resources/collaborator/methods/Create'
        update: []
        delete:
        - $ref: '#/components/x-stackQL-resources/collaborator/methods/Delete'
        exec: []
    team-app-collaborator:
      id: heroku.collaborators.team-app-collaborator
      name: team-app-collaborator
      title: Team App Collaborator
      methods:
        Create:
          operation:
            $ref: '#/paths/~1teams~1apps~1{app_identity}~1collaborators/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        Delete:
          operation:
            $ref: '#/paths/~1teams~1apps~1{team_app_identity}~1collaborators~1{team_app_collaborator_identity}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        Info:
          operation:
            $ref: '#/paths/~1teams~1apps~1{team_app_identity}~1collaborators~1{team_app_collaborator_identity}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        Update:
          operation:
            $ref: '#/paths/~1teams~1apps~1{team_app_identity}~1collaborators~1{team_app_collaborator_identity}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        List:
          operation:
            $ref: '#/paths/~1teams~1apps~1{team_app_identity}~1collaborators/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/team-app-collaborator/methods/Info'
        - $ref: '#/components/x-stackQL-resources/team-app-collaborator/methods/List'
        insert:
        - $ref: '#/components/x-stackQL-resources/team-app-collaborator/methods/Create'
        update:
        - $ref: '#/components/x-stackQL-resources/team-app-collaborator/methods/Update'
        delete:
        - $ref: '#/components/x-stackQL-resources/team-app-collaborator/methods/Delete'
        exec: []
security:
- herokuAuth: []
