openapi: 3.0.0
info:
  title: Heroku Platform API - Platform
  description: The platform API empowers developers to automate, extend and combine Heroku with other services.
  version: v0
servers:
- url: https://api.heroku.com
paths:
  /regions/{region_identity}:
    get:
      summary: Info
      description: Info for existing region.
      operationId: regionInfo
      tags:
      - platform
      parameters:
      - name: region_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of region.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/region'
      x-stackQL-resource: region
      x-stackQL-method: Info
      x-stackQL-verb: select
  /regions:
    get:
      summary: List
      description: List existing regions.
      operationId: regionList
      tags:
      - platform
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/region'
                type:
                - array
      x-stackQL-resource: region
      x-stackQL-method: List
      x-stackQL-verb: select
  /stacks/{stack_identity}:
    get:
      summary: Info
      description: Stack info.
      operationId: stackInfo
      tags:
      - platform
      parameters:
      - name: stack_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of stack.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stack'
      x-stackQL-resource: stack
      x-stackQL-method: Info
      x-stackQL-verb: select
  /stacks:
    get:
      summary: List
      description: List available stacks.
      operationId: stackList
      tags:
      - platform
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/stack'
                type:
                - array
      x-stackQL-resource: stack
      x-stackQL-method: List
      x-stackQL-verb: select
  /apps/{app_identity}/available-stacks:
    get:
      summary: List by App
      description: List available app stacks for an app.
      operationId: stackListByApp
      tags:
      - platform
      parameters:
      - name: app_identity
        in: path
        required: true
        schema:
          type: string
        description: Unique identifier for identity of app.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/stack'
                type:
                - array
      x-stackQL-resource: stack
      x-stackQL-method: ListByApp
      x-stackQL-verb: select
components:
  schemas:
    region:
      description: A region represents a geographic location in which your application may run.
      type:
      - object
      properties:
        country:
          $ref: '#/components/schemas/country'
        created_at:
          $ref: '#/components/schemas/created_at'
        description:
          $ref: '#/components/schemas/description'
        id:
          $ref: '#/components/schemas/id'
        locale:
          $ref: '#/components/schemas/locale'
        name:
          $ref: '#/components/schemas/name'
        private_capable:
          $ref: '#/components/schemas/private_capable'
        provider:
          $ref: '#/components/schemas/provider'
        updated_at:
          $ref: '#/components/schemas/updated_at'
    stack:
      description: Stacks are the different application execution environments available in the Heroku platform.
      type:
      - object
      properties:
        default:
          $ref: '#/components/schemas/default'
        created_at:
          $ref: '#/components/schemas/created_at'
        id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/name'
        state:
          $ref: '#/components/schemas/state'
        updated_at:
          $ref: '#/components/schemas/updated_at'
    default:
      description: indicates this stack is the default for new apps
      readOnly: true
      type:
      - boolean
    created_at:
      description: when stack was introduced
      format: date-time
      readOnly: true
      type:
      - string
    id:
      description: unique identifier of stack
      format: uuid
      readOnly: true
      type:
      - string
    name:
      description: unique name of stack
      readOnly: true
      type:
      - string
    state:
      description: 'availability of this stack: beta, deprecated or public'
      readOnly: true
      type:
      - string
    updated_at:
      description: when stack was last modified
      format: date-time
      readOnly: true
      type:
      - string
  securitySchemes:
    herokuAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
  x-stackQL-resources:
    region:
      id: heroku.platform.region
      name: region
      title: Region
      methods:
        Info:
          operation:
            $ref: '#/paths/~1regions~1{region_identity}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        List:
          operation:
            $ref: '#/paths/~1regions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/region/methods/Info'
        - $ref: '#/components/x-stackQL-resources/region/methods/List'
        insert: []
        update: []
        delete: []
        exec: []
    stack:
      id: heroku.platform.stack
      name: stack
      title: Stack
      methods:
        Info:
          operation:
            $ref: '#/paths/~1stacks~1{stack_identity}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        List:
          operation:
            $ref: '#/paths/~1stacks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        ListByApp:
          operation:
            $ref: '#/paths/~1apps~1{app_identity}~1available-stacks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/stack/methods/Info'
        - $ref: '#/components/x-stackQL-resources/stack/methods/List'
        - $ref: '#/components/x-stackQL-resources/stack/methods/ListByApp'
        insert: []
        update: []
        delete: []
        exec: []
security:
- herokuAuth: []
